options:
  layouts: './lib/layouts/**/*.hbs'
  defaultLayout: 'default'
data:
    - './lib/data/config.yml'
images:
  src: './../docs/**/*.png'
  target: './../tutorial/'
docs:
  target: './../tutorial'
