tutorial:
  version: 0.4.1
options:
  layouts: './lib/layouts/**/*.hbs'
  defaultLayout: 'default-md.hbs'
images:
  src: './../docs/images/**/*.png'
  target: './../tutorial/images'
docs:
  target: './../tutorial'
