options:
  layouts: './lib/layouts/**/*.hbs'
  defaultLayout: 'default'
data:
    - './lib/data/config.yml'
images:
  src: './../docs/images/**/*.png'
  target: './../tutorial/images'
docs:
  target: './../tutorial'
